# Load fzf auto-completion and key bindings
export FZF_DEFAULT_COMMAND='rg --files --follow --hidden'
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Source prompt
eval "$(starship init bash)"

# Set up Heroku autocomplete
HEROKU_AC_BASH_SETUP_PATH=~/Library/Caches/heroku/autocomplete/bash_setup && \
  test -f $HEROKU_AC_BASH_SETUP_PATH && \
  source $HEROKU_AC_BASH_SETUP_PATH;

# Utility functions
mkcdir() {
  mkdir -p -- "$1" && cd -P -- "$1"
}
