# Use Neovim instead of Vim or Vi
alias v{,i,im}='nvim'

# Enable vi mode
set -o vi

# Enable globstar, aka ./**/* matching
shopt -s globstar

# Aliases
alias cat='bat'
alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'
alias grp='grep --color -n -C 1'
alias help='tldr'
alias ll='ls -la'
alias mux='tmuxinator'
alias ping='prettyping --nolegend'
alias top='htop'

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
