#!/usr/bin/env bash

# Don't check mail when opening terminal
unset MAILCHECK

# Allow using coreutils commands and man pages with their normal names
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Use Neovim as preferred editor
export EDITOR=nvim
export VISUAL=nvim
export VIMCONFIG=~/.config/nvim
export VIMDATA=~/.local/share/nvim

# Configure gpg-agent
gpgconf --launch gpg-agent
export SSH_AUTH_SOCKET=$HOME/.gnupg/S.gpg-agent.ssh
export GPG_TTY=$(tty)

# Source prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=/usr/local/opt/bash-git-prompt/share
  GIT_PROMPT_ONLY_IN_REPO=0
  GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=0
  GIT_PROMPT_THEME=Custom
  GIT_PROMPT_THEME_FILE=~/.git-prompt-colors.bash
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

# Source Bash autocompletion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# Source Git autocompletion
[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash

# Source local profile
[ -f ~/.bash_profile.local ] && source ~/.bash_profile.local

# Source Sensible Bash
[ -f ~/.sensible.bash ] && source ~/.sensible.bash

# Load fzf auto-completion and key bindings
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load RVM into a shell session as a function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Load NVS
export NVS_HOME="$HOME/.nvs"
[ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh"

# Soruce Homebrew's completions
if type brew 2&>/dev/null; then
  for completion_file in $(brew --prefix)/etc/bash_completion.d/*; do
    source "$completion_file"
  done
fi

# Configure MySQL
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

# Configure Python 3
export PATH="/usr/local/opt/python@3/bin:$PATH"

# Configure Go
export GOPATH="$HOME/.go"

# Load colors
eval $(dircolors -b $HOME/.dircolors)

# Load jump
eval "$(jump shell)"

# Use Neovim instead of Vim or Vi
alias v{,i,im}='nvim'

# Enable vi mode
set -o vi

# Aliases
alias cat='bat'
alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'
alias g='git'
alias grp='grep --color -n -C 1'
alias help='tldr'
alias ll='ls -lAh'
alias ls='ls --color=auto'
alias mux='tmuxinator'
alias ping='prettyping --nolegend'
alias top='htop'

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Use English for command line tools
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
