# General
alias cat='bat'
alias cl='clear'
alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'
alias help='tldr'
alias ll='ls -lAh'
alias ls='gls --color'
alias mux='tmuxinator'
alias ping='prettyping --nolegend'
alias top='htop'
alias v{,i,im}='nvim'

# Brew
alias bcin='brew cask install'
alias bcl='brew cleanup'
alias bcls='brew cask list'
alias bcrm='brew cask uninstall'
alias bcup='brew cask upgrade'
alias bdr='brew doctor'
alias bin='brew install'
alias binf='brew info'
alias bls='brew list'
alias bout='brew outdated'
alias brm='brew uninstall'
alias bsr='brew search'
alias bup='brew upgrade'

# Bundler
alias be='bundle exec'
alias bi='bundle install'
alias bl='bundle list'
alias bp='bundle package'
alias bu='bundle update'

# macOS
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'

# Rails
alias r='rails'
alias rc='rails c'
alias rdbm='rails db:migrate'
alias rs='rails s'

# Tmux
alias txa='tmux a -t'
alias txl='tmux ls'
alias txn='tmux new -s'

# Yarn
alias ya='yarn'
alias yaa='yarn add'
alias yaad='yarn add --dev'
alias yaga='yarn global add'
alias yagrm='yarn global remove'
alias yai='yarn init'
alias yarm='yarn remove'
alias yaru='yarn run'
alias yat='yarn test'
