" Plugins {{{
  " Install vim-plug automatically
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
  call plug#begin()

  " Theme and appearance
  Plug 'ayu-theme/ayu-vim'
  Plug 'vim-airline/vim-airline'

  " File navigation & utilities
  Plug 'scrooloose/nerdtree'
  Plug 'Xuyuanp/nerdtree-git-plugin'
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-eunuch'
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
  Plug 'junegunn/fzf.vim'
  Plug 'jremmen/vim-ripgrep'

  " Git
  Plug 'tpope/vim-fugitive'
  Plug 'airblade/vim-gitgutter'
  Plug 'tpope/vim-rhubarb'

  " Code editing, formatting and completion
  Plug 'Valloric/YouCompleteMe', { 'do': '!./install.py --clang-completer --js-completer' }
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-abolish'
  Plug 'prettier/vim-prettier', { 'do': 'yarn install' }
  Plug 'tpope/vim-surround'
  Plug 'jiangmiao/auto-pairs'
  Plug 'terryma/vim-multiple-cursors'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'w0rp/ale'
  Plug 'alvan/vim-closetag'
  Plug 'mattn/emmet-vim'
  Plug 'ludovicchabant/vim-gutentags'

  " Ruby + frameworks
  Plug 'tpope/vim-rails'
  Plug 'tpope/vim-bundler'
  Plug 'tpope/vim-endwise'
  Plug 'janko-m/vim-test'

  " JavaScript + frameworks
  Plug 'styled-components/vim-styled-components', { 'branch': 'main' }
  Plug 'posva/vim-vue'
  Plug 'maxmellon/vim-jsx-pretty'
  Plug 'kristijanhusak/vim-js-file-import', { 'do': 'npm install' }

  " GraphQL
  Plug 'jparise/vim-graphql'
  call plug#end()
" }}}
" General settings {{{
  set nocompatible                    " Allow Vim-only settings (must be first)
  set backspace=indent,eol,start      " Allow backspace in insert mode
  set ttimeoutlen=10                  " Avoid pausing when leaving insert mode
  set visualbell                      " No sounds
  set laststatus=2                    " Always display a status line
  set cmdheight=2                     " Avoid “Press <ENTER> to continue” prompt
  set autoread                        " Reload files changed outside of Vim
  set history=1000                    " Number of commands to remember
  set undolevels=1000                 " Number of undo levels
  set noshowmode                      " Do not show mode
  set hidden                          " Hide buffers when abandoned
  set mouse=a                         " Enable mouse support
" }}}
" Colors {{{
  set termguicolors                   " Enable true colors support
  let ayucolor="mirage"               " Other options: 'light' or 'dark'
  colorscheme ayu
  syntax enable

  " Make 'listchars' visible until https://git.io/fxZSl is merged
  hi NonText ctermfg=130 guifg=#3D4751
" }}}
" UI Layout {{{
  set number                          " Show line numbers
  set showcmd                         " Show command in bottom bar
  set nocursorline                    " Highlight current line
  set wildmenu
  set lazyredraw
  set showmatch                       " Higlight matching parenthesis
  set splitright                      " Open new splits on the right
  set list
  set listchars=tab:▸\ ,trail:·       " Display tabs and trailing spaces
  set scrolloff=5                     " Start scrolling when close to margin
  set textwidth=80
  set colorcolumn=+1
  set fillchars+=vert:┃
" }}}
" Behavior {{{
  " Open :help in a new tab
  cnoreabbrev <expr> help getcmdtype() == ":" && getcmdline() == 'help' ?
    \ 'tab help' : 'help'
" }}}
" Spaces & Tabs {{{
  set tabstop=2                       " Two-space tab
  set expandtab                       " Use spaces for tabs
  set softtabstop=2
  set shiftwidth=2
  set modelines=1
  set autoindent smartindent          " Auto-indent based on previous line
  filetype indent plugin on           " Enable file type detection
" }}}
" Searching {{{
  set ignorecase                      " Ignore case when searching
  set incsearch                       " Search as you type
  set hlsearch                        " Highlight all matches
" }}}
" Folding {{{
  set foldmethod=indent               " Fold based on indent level
  set foldnestmax=10                  " Max 10 depth
  set foldenable                      " Do not fold files by default on open
  nnoremap <space> za
  set foldlevelstart=10               " Start with fold level of 10
" }}}
" Swap files {{{
  set noswapfile
  set nobackup
  set nowb
" }}}
" Auto commands {{{
  " Trim whitespace when saving
  autocmd BufWritePre * :call TrimWhitespace()

  " Set specific type based on file type
  autocmd FileType gitcommit setlocal textwidth=72
  autocmd FileType gitcommit setlocal spell
" }}}
" Key bindings {{{
  " Grep word under cursor
  nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

  " Cycle through listed buffers
  nnoremap <Tab> :bnext<CR>
  nnoremap <S-Tab> :bprevious<CR>

  " Vim. Live it.
  nnoremap <up> <nop>
  nnoremap <down> <nop>
  nnoremap <left> <nop>
  nnoremap <right> <nop>
  inoremap <up> <nop>
  inoremap <down> <nop>
  inoremap <left> <nop>
  inoremap <right> <nop>

  " Toggle NERDTree
  map <silent> <C-p><C-p> :NERDTreeToggle<CR>

  " Easy ESC with jk in insert mode
  inoremap jk <esc>
  snoremap jk <esc>

  " Toggle invisibles
  nmap <leader>l :set list!<CR>

  " Search for stuff
  nnoremap <C-p> :Files<CR>
  nnoremap <Leader>b :Buffers<CR>
  nnoremap <Leader>h :History<CR>

  " Symbols for tabstops and EOLs
  set listchars=tab:▸\ ,eol:¬
" }}}
" Plugins configuration {{{
  " vim-airline
  let g:airline_powerline_fonts=1
  let g:airline#extensions#tabline#enabled=1

  " netrw
  let g:loaded_netrw=1
  let g:loaded_netrwPlugin=1

  " NERDTree
  let NERDTreeAutoDeleteBuffer=1
  let NERDTreeDirArrows=1
  let NERDTreeMinimalUI=1
  let NERDTreeQuitOnOpen=1
  let NERDTreeShowHidden=1
  let g:NERDTreeHijackNetrw=0

  " ALE
  let g:ale_lint_on_text_changed='never'
  let g:ale_fix_on_save=1
  let g:ale_fixers = {
  \  '*': ['remove_trailing_lines', 'trim_whitespace'],
  \  'javascript': ['prettier', 'eslint'],
  \}

  " vim-test
  nmap <silent> t<C-n> :TestNearest<CR>
  nmap <silent> t<C-f> :TestFile<CR>
  nmap <silent> t<C-s> :TestSuite<CR>
  nmap <silent> t<C-l> :TestLast<CR>
  nmap <silent> t<C-g> :TestVisit<CR>

  " vim-closetag
  let g:closetag_filenames = '*.html,*.vue,*.js'
  let g:closetag_emptyTags_caseSensitive = 1

  " emmett-vim
  let g:user_emmet_leader_key=','

  " vim-js-file-import
  let g:js_file_import_from_root = 1

  " gutentags
  let g:gutentags_exclude_filetypes = ['gitcommit', 'gitconfig', 'gitrebase', 'gitsendemail', 'git']
  " }}}
" Custom functions {{{
  " Trim trailing whitespace without side-effects
  function! TrimWhitespace()
    let l:save=winsaveview()
    %s/\s\+$//e
    call winrestview(l:save)
  endfunction
" }}}
" vim:foldmethod=marker:foldlevel=0
