alias c     'clear'
alias be    'bundle exec'
alias bi    'bundle install'
alias bl    'bundle list'
alias brcl  'brew cleanup'
alias brcu  'brew cu'
alias brd   'brew doctor'
alias brin  'brew install'
alias brinf 'brew info'
alias brls  'brew list'
alias brout 'brew outdated'
alias brs   'brew search'
alias brun  'brew uninstall'
alias brup  'brew upgrade'
alias bu    'bundle update'
alias cat   'bat'
alias cp    'cp -iv'
alias df    'duf'
alias fldns 'sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias mkdir 'mkdir -pv'
alias mv    'mv -iv'
alias ping  'gping'
alias r     'rails'
alias rc    'rails console'
alias rdbm  'rails db:migrate'
alias rs    'rails server'
alias serve 'npx http-server --port'
alias top   'htop'
alias v     'nvim'
alias ya    'yarn'
alias yaa   'yarn add'
alias yaad  'yarn add --dev'
alias yaga  'yarn global add'
alias yagrm 'yarn global remove'
alias yai   'yarn init'
alias yarm  'yarn remove'
alias yaru  'yarn run'
alias yat   'yarn test'
alias zj    'zellij'

# Aliases for .gitaliases
alias ga    'git a'
alias gamd  'git amd'
alias gb    'git b'
alias gc    'git c'
alias gca   'git ca'
alias gco   'git co'
alias gcp   'git cp'
alias gd    'git d'
alias gdc   'git dc'
alias gf    'git f'
alias gfp   'git fp'
alias gl    'git l'
alias glc   'git lc'
alias gp    'git p'
alias gr    'git r'
alias grc   'git rc'
alias gst   'git st'
alias gsth  'git sth'
alias gu    'git u'
alias gup   'git up'
