alias be    'bundle exec'
alias brup  'brew upgrade'
alias bi    'bundle install'
alias bl    'bundle list'
alias brcl  'brew cleanup'
alias brd   'brew doctor'
alias brin  'brew install'
alias brinf 'brew info'
alias brls  'brew list'
alias brout 'brew outdated'
alias brs   'brew search'
alias brun  'brew uninstall'
alias bu    'bundle update'
alias cat   'bat'
alias cp    'cp -iv'
alias df    'duf'
alias fldns 'sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder;'
alias mkdir 'mkdir -pv'
alias mv    'mv -iv'
alias ping  'prettyping --nolegend'
alias r     'rails'
alias rc    'rails console'
alias rdbm  'rails db:migrate'
alias rs    'rails serve'
alias serve 'npx http-server --port'
alias tmxtr 'tmuxinator start'
alias top   'htop'
alias txa   'tmux attach-session -t'
alias txk   'tmux kill-session -t'
alias txl   'tmux list-sessions'
alias txn   'tmux new -s'
alias v     'nvim'
alias ya    'yarn'
alias yaa   'yarn add'
alias yaad  'yarn add --dev'
alias yaga  'yarn global add'
alias yagrm 'yarn global remove'
alias yai   'yarn init'
alias yarm  'yarn remove'
alias yaru  'yarn run'
alias yat   'yarn test'
