# Prefix

unbind-key C-b
set -g prefix C-a

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Key bindings

unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi "v" send-keys -X begin-selection
bind-key -T copy-mode-vi "y" send-keys -X copy-pipe-and-cancel "pbcopy"
setw -g mode-keys vi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Pop-ups

bind -r ";" display-popup -d "#{pane_current_path}" -w80% -h80% -E -s "fg=#636da6,bg=#1b1d2e" lazygit

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Mouse

set -g mouse on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Colors

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Indexing

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Status line: theme & plugins

set -g @powerkit_theme "moonlight"
set -g @powerkit_theme_variant "default"
set -g @powerkit_plugins "netspeed"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Status line: style

set -g @powerkit_edge_separator_style "same"
set -g @powerkit_separator_style "slant"
set -g @powerkit_status_position "bottom"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Plugins

set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "tmux-plugins/tpm"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Plugin manager

run "~/.config/tmux/plugins/tpm/tpm"
