# For more information about the configurations used in this file, please see
# GitHub actions documentation.
#
# https://help.github.com/en/github/automating-your-workflow-with-github-actions/

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

name: tests

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: ./tests/shellcheck.sh
